name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: --privileged
        ports:
          - 8000:8000
          - 8001:8001

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cloudshort-backend:latest ./cloudshort-backend
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cloudshort-backend:latest

      - name: Build and push mlservice image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/ml-service:latest ./ml-service
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/ml-service:latest

      - name: Deploy with Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d --build
